services:
  dashboard:
    build:
      context: .

    container_name: palworld-dashboard
    restart: unless-stopped

    env_file:
      - .env

    environment:
      PSUTIL_PROCFS_PATH: /host/proc
      HOST_ROOT_PATH: /host/root

    ports:
      - "127.0.0.1:8000:8000"

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro

    networks:
      - palworld-existing

networks:
  palworld-existing:
    external: true
    name: palworld_default
