services:
  dashboard:
    build:
      context: .

    container_name: palworld-dashboard
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "127.0.0.1:8000:8000"

    networks:
      - palworld-existing

networks:
  palworld-existing:
    external: true
    name: palworld_default
