server {
    listen 8080;
    server_tokens off;

    location = /v1/api/info {
        limit_except GET { deny all; }
        proxy_pass http://palworld-server:8212;
        proxy_set_header Host palworld-server;
        proxy_pass_request_headers on;
    }

    location = /v1/api/metrics {
        limit_except GET { deny all; }
        proxy_pass http://palworld-server:8212;
        proxy_set_header Host palworld-server;
        proxy_pass_request_headers on;
    }

    location = /v1/api/players {
        limit_except GET { deny all; }
        proxy_pass http://palworld-server:8212;
        proxy_set_header Host palworld-server;
        proxy_pass_request_headers on;
    }

    location / {
        return 404;
    }
}
